version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - BS_USERNAME=${BS_USERNAME}
      - BS_ACCESS_KEY=${BS_ACCESS_KEY}

  testrunner:
    build:
      context: .
      dockerfile: Dockerfile.testrunner
    environment:
      - BS_USERNAME=${BS_USERNAME}
      - BS_ACCESS_KEY=${BS_ACCESS_KEY}
    # To run a test manually inside container (override entrypoint)
    # command: ["android", "Cristiano Ronaldo"]
    # or set args when running
