FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

ENV BS_USERNAME=your_browserstack_username
ENV BS_ACCESS_KEY=your_browserstack_access_key

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
