FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tests1 ./tests

ENV BS_USERNAME=your_browserstack_username
ENV BS_ACCESS_KEY=your_browserstack_access_key

ENTRYPOINT ["node", "tests/onboarding1.spec.js"]
