name: AppWright Test

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install CLI dependencies
        run: |
          pip install -r qg-job/requirements.txt

      - name: Build backend Docker image
        run: |
          docker build -t qg-job-server ./qg-job_server

      - name: Run backend server container
        run: |
          docker run -d -p 8000:8000 --name backend qg-job-server
          sleep 5

      - name: Submit job via CLI
        run: |
          JOB_JSON=$(python qg-job/qg-job.py submit --org-id qualgent --app-version-id xyz123 --test tests/onboarding.spec.js --priority 1 --target emulator)
          echo "$JOB_JSON"
          echo "$JOB_JSON" > output.json
          JOB_ID=$(echo "$JOB_JSON" | python -c "import sys, json; print(json.load(sys.stdin)['job_id'])")
          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV

      - name: Poll for job completion
        run: |
          sleep 3
          python qg-job/qg-job.py status --job-id ${{ env.JOB_ID }}
