name: AppWright Test

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run qgjob submit
        run: |
          set -e  # Exit if anything fails
          JOB_JSON=$(python qg-job/qg-job.py submit --org-id qualgent --app-version-id xyz123 --test tests/onboarding.spec.js --priority 1 --target emulator)
          echo "$JOB_JSON"
          echo "$JOB_JSON" > output.json
          JOB_ID=$(echo "$JOB_JSON" | jq -r '.job_id')
          echo "Job ID: $JOB_ID"
          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV


      - name: Poll for job completion
        run: |
          python qg-job/qg-job.py status --job-id ${{ env.JOB_ID }} --wait
